// GENERATED by tools/generate-dossiers.ts. Do not edit by hand.
//
// One import per committed dossier, so `../dossiers.ts` keeps no list of its
// own to fall out of step with this directory. `--check` fails when a file
// here is missing from this list.

import type { DossierFile } from '../model.ts';

export const DOSSIER_FILES: readonly DossierFile[] = [];
