// Is the phosphor still in one home?
//
//   node --experimental-strip-types tools/palette.ts generate   # write palette.css
//   node --experimental-strip-types tools/palette.ts check      # the gate
//
// (also `npm run generate:palette` and `npm run palette:check`, the latter part
// of `npm run check`.)
//
// Two claims, both from docs/TODO/93:
//
//   1. `src/palette.css` is what `src/palette.ts` says it is. It is generated,
//      so an edit to the stylesheet is an edit that is about to be overwritten,
//      and the gate says so before a reviewer has to notice.
//
//   2. Nobody else spells a palette colour. Fourteen homes in three spellings
//      is what this item found, and hand-sweeping them proves nothing about
//      the fifteenth. The scan covers `#4dff5c`, `0x4dff5c` and the decimal
//      `77, 255, 92` that an `rgba()` uses, because all three were in the tree.
//
// The exemption list below is the review surface — the same shape as
// `tools/sizes.mjs`'s ALLOWED and `tools/portability.mjs`'s PLATFORM. A copy
// that cannot import is allowed to exist; a copy that does not say it is one
// is not.

import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { CSS_VARS, HUD, DOC, TINT, channels } from '../src/palette.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'src');
const generatedPath = join(src, 'palette.css');

/**
 * Files allowed to spell a palette colour, each with why.
 *
 * A reason is not "it has one". It is why the value cannot be imported from
 * `src/palette.ts` — which, in a project where everything else is TypeScript
 * reaching one module, is a short list.
 */
const ALLOWED: Record<string, string> = {
  'src/palette.ts': 'the one home',
  'src/palette.css': 'GENERATED from it, and checked against it above',
  // Python, run offline by hand, with no route to a .ts module. A stated copy
  // naming its source is the honest answer and is what the file attempts; the
  // check above is what makes the claim true rather than merely written down.
  'tools/posterise.py': 'Python: it cannot import TypeScript. Its copy is checked below.',
  // The gate cannot describe what it forbids without writing it down. This is
  // the one file where a palette colour appears in prose and nowhere in a
  // value — every literal below is built from src/palette.ts at run time.
  'tools/palette.ts': 'the gate: it names the spellings it hunts for',
  // The only file where writing a colour out by hand is the POINT: it pins the
  // rgba() spellings that were in the tree before docs/TODO/93, so that
  // `alpha()` can be tested against what it replaced rather than against
  // itself. Testing a generator with its own output proves nothing.
  'test/palette.test.ts': 'it pins the spellings the sweep replaced, verbatim',
};

/** Every colour the gate defends, by the name it should be reached by. */
const GUARDED: ReadonlyArray<readonly [string, string]> = [
  ...Object.entries(HUD).map(([k, v]) => [`HUD.${k}`, v] as const),
  ...Object.entries(DOC).map(([k, v]) => [`DOC.${k}`, v] as const),
  ...Object.entries(TINT).map(([k, v]) => [`TINT.${k}`, v] as const),
];

// --- generate ----------------------------------------------------------------

/**
 * The stylesheet, as the one home implies it.
 *
 * Each colour lands twice: once as itself, and once as a bare `r, g, b` triple
 * so that `rgba(var(--hud-green-rgb), 0.35)` can exist. That spelling rather
 * than `color-mix(in srgb, var(--hud-green) 35%, transparent)` because it
 * produces the exact bytes the sixteen hand-written `rgba()`s produced, which
 * is what lets docs/TODO/93 claim nothing looks different; `color-mix` is a
 * conversion through a colour space and is only nearly the same.
 */
export function renderStylesheet(): string {
  const lines = CSS_VARS.flatMap(([name, colour]) => {
    const [r, g, b] = channels(colour);
    return [`  --${name}: ${colour};`, `  --${name}-rgb: ${r}, ${g}, ${b};`];
  });
  return [
    '/*',
    ' * GENERATED by tools/palette.ts from src/palette.ts. Do not edit by hand.',
    ' * Regenerate with `npm run generate:palette`; `npm run palette:check` fails',
    ' * if this file and its source have drifted.',
    ' *',
    ' * Every stylesheet in the project @imports this one and none of them define',
    ' * a colour, so a page that loads only its own stylesheet is still coloured —',
    ' * which viewer.css used to depend on style.css having been loaded for.',
    ' *',
    ' * The `-rgb` twin of each colour is for alpha: `rgba(var(--hud-green-rgb),',
    ' * 0.35)`. CSS cannot call `alpha()` in palette.ts, so it gets the channels.',
    ' */',
    '',
    ':root {',
    ...lines,
    '}',
    '',
  ].join('\n');
}

function generate(): void {
  writeFileSync(generatedPath, renderStylesheet());
  console.log(`palette: wrote src/palette.css — ${CSS_VARS.length} colours`);
}

// --- check -------------------------------------------------------------------

interface Finding { file: string; line: number; text: string; message: string }

const walk = (dir: string): string[] =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const path = join(dir, e.name);
    if (e.isDirectory()) return walk(path);
    return /\.(ts|css|html|py|mjs)$/.test(e.name) ? [path] : [];
  });

/**
 * Every way this codebase has been caught writing one colour.
 *
 * `#4dff5c` and `0x4dff5c` share a body, so one pattern with an optional
 * prefix catches both — and the prefix is optional rather than required
 * because a bare `4dff5c` in a comment is still a second home in waiting. The
 * decimal form allows any spacing, since the tree held `rgba(77, 255, 92,` and
 * `rgba(77,255,92,` alike.
 */
function spellings(colour: string): RegExp[] {
  const body = colour.replace('#', '');
  const [r, g, b] = channels(colour);
  return [
    new RegExp(`(?:#|0x)?${body}`, 'i'),
    new RegExp(`\\b${r},\\s*${g},\\s*${b}\\b`),
  ];
}

/** Colour literals spelled outside the one home. */
export function strayColours(files: string[]): Finding[] {
  const findings: Finding[] = [];
  for (const path of files) {
    const file = relative(root, path).replaceAll('\\', '/');
    if (ALLOWED[file]) continue;
    const lines = readFileSync(path, 'utf8').split('\n');
    lines.forEach((text, i) => {
      for (const [name, colour] of GUARDED) {
        if (!spellings(colour).some((p) => p.test(text))) continue;
        findings.push({
          file, line: i + 1, text: text.trim(),
          message: `spells ${colour} — import ${name} from src/palette.ts`,
        });
        return; // one finding a line; the first is enough to send someone here
      }
    });
  }
  return findings;
}

/**
 * `posterise.py`'s stated copy, checked against what it claims to copy.
 *
 * The file says "the game's greens, from src/style.css" over three values, and
 * two of them were real copies while the third — `DARK` — was the tool's own
 * invention presented as one (docs/TODO/93). A stated copy is only honest if
 * something reads both ends, so this does.
 */
export function posteriseCopy(): Finding[] {
  const file = 'tools/posterise.py';
  const path = join(root, file);
  if (!existsSync(path)) return [];
  const source = readFileSync(path, 'utf8');
  const findings: Finding[] = [];
  for (const [name, colour] of [['DIM', HUD.dim], ['BRIGHT', HUD.green]] as const) {
    const [r, g, b] = channels(colour);
    const declared = new RegExp(
      `^${name}\\s*=\\s*\\(\\s*0x([0-9a-f]{2})\\s*,\\s*0x([0-9a-f]{2})\\s*,\\s*0x([0-9a-f]{2})`,
      'im',
    );
    const match = source.match(declared);
    const line = source.slice(0, match?.index ?? 0).split('\n').length;
    if (!match) {
      findings.push({
        file, line: 1, text: `${name} = ...`,
        message: `no ${name} = (0x.., 0x.., 0x..) to check against the palette`,
      });
      continue;
    }
    const got = [match[1], match[2], match[3]].map((h) => parseInt(h, 16));
    if (got[0] !== r || got[1] !== g || got[2] !== b) {
      findings.push({
        file, line, text: match[0],
        message: `${name} claims to copy ${colour} but is`
          + ` (${got.map((n) => `0x${n.toString(16).padStart(2, '0')}`).join(', ')})`,
      });
    }
  }
  return findings;
}

function check(): void {
  // `test/` is scanned too, and not as an afterthought: a colour asserted in a
  // test is a second home in the one place nobody thinks to look for one, and
  // it is the home that would quietly go on passing after the real value moved.
  const findings = [
    ...strayColours([
      ...walk(src), ...walk(join(root, 'tools')), ...walk(join(root, 'test')),
    ]),
    ...posteriseCopy(),
  ];

  const wanted = renderStylesheet();
  const current = existsSync(generatedPath) ? readFileSync(generatedPath, 'utf8') : null;
  if (current !== wanted) {
    findings.unshift({
      file: 'src/palette.css', line: 1, text: '',
      message: 'stale or missing; run npm run generate:palette',
    });
  }

  for (const f of findings) {
    console.error(`ERROR ${f.file}:${f.line} ${f.message}`);
    if (f.text) console.error(`      ${f.text}`);
  }
  if (findings.length) {
    console.error(`palette: ${findings.length} error(s)`);
    process.exitCode = 1;
  } else {
    console.log(`palette: ${GUARDED.length} colours, one home — palette.css current`);
  }
}

// --- cli ---------------------------------------------------------------------

// Only when RUN, never when imported. `test/palette.test.ts` imports the three
// exported functions above to drive the gate with input that must be rejected,
// and without this guard that import reaches the argv dispatch below, finds no
// command, and sets `process.exitCode = 1` — which made `npm test` print
// "3577 passed, 0 failed" and then exit non-zero. A test suite that fails while
// reporting success is worse than one that fails.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const command = process.argv[2];
  if (command === 'generate') generate();
  else if (command === 'check') check();
  else {
    console.error('usage: palette.ts <generate | check>');
    process.exitCode = 1;
  }
}
