// Build the extended-description prompt for every system in a galaxy.
//
//   node --experimental-strip-types tools/system-prompts.ts [galaxy] [--json]
//
// Writes nothing. Prints a sample so the prompts can be read before anyone
// spends money; with --json it emits the manifest tools/generate-descriptions.ts
// consumes.
//
// Same bargain as tools/species-prompts.ts, and for the same reason: everything
// here derives from the 1984 seeds, so the manifest is reproducible — same
// galaxy in, same prompts and hashes out. No model runs at build time and none
// can, because the game deploys as a static site.
//
// The 1984 data is the source of truth and this is a decorator on top of it.
// galaxy.ts and goatsoup.ts are byte-matched to the original (invariant 4);
// nothing here edits them, and the goat-soup line is an INPUT to the prompt
// rather than something to be rewritten.

import {
  generateGalaxy, speciesName, ECONOMY_NAMES, GOVERNMENT_NAMES, type StarSystem,
} from '../src/galaxy/galaxy.ts';
import { planetDescription } from '../src/galaxy/goatsoup.ts';

/**
 * Bumped by hand when the rules below change in a way that should invalidate
 * every committed description.
 *
 * It is part of each system's prompt hash, so bumping it makes `--check` fail
 * for the whole galaxy at once and the regeneration is deliberate. Without it
 * a rules edit would silently leave 256 records generated under the old ones,
 * which is the "one rule with two homes" failure wearing a different hat.
 */
export const PROMPT_VERSION = 3;

/**
 * The rules, in full, shared by every request.
 *
 * Most of this is negative space, and that is the point. The model is good at
 * atmospheric prose unprompted; what it is not good at unprompted is knowing
 * which claims this game can contradict on the very next screen. A paragraph
 * saying furs fetch a good price here is checkable against generateMarket(),
 * and wrong about half the time — so the prohibition has to be explicit,
 * because "write a nice description" does not imply it.
 */
export const SYSTEM_PROMPT = `You write short gazetteer entries for star systems in a space trading game, in the style of a printed reference work carried aboard ship. Dry, matter-of-fact, specific. You are describing places that exist, not selling them.

You will be given the established facts about one system. Every one of them is fixed and true. Your entry elaborates on them and must never contradict, soften or restate them.

The "known for" line is generated by the game itself and is canon. Treat it as the seed of the entry: if it says the world is fabled for its exotic goat soup, then it is, and the entry is about a world where that is so.

Write two things:

DESCRIPTION — two to four sentences on the world. Pick the two or three things that matter most for THIS place and write about those; a world defined by its weather and a world defined by its factories should not be described in the same order or at the same length. Draw on any of: terrain, climate, what it grows or makes, how its settlements are laid out, what it is known for, what has happened to it.

INHABITANTS — one to three sentences on the people. Ground it in how this particular government and economy have shaped their work and their character.

Absolute rules:

1. No digits and no written-out numbers. Not populations, not distances, not dates, not prices, not years. The statistics are already on screen beside your text; a number in the prose is a fact that can disagree with them.
2. No second person. Never "you", "your", "yours". Write about the world, not the reader.
3. Say nothing about the price, availability or profitability of any trade good. The game sets prices and will contradict you.
4. Say nothing about what equipment, weapons or ship parts can be bought here. The game decides that from the tech level.
5. Do not name any other star system, and do not invent proper nouns for people, companies, rulers or wars. You may name local features — a sea, a range, a city district — sparingly.
6. Do not mention the player, ships arriving, trading, piracy rates, police or bounties.
7. Never use these words: bustling, vibrant, nestled, boasts, testament, tapestry, myriad, denizens, teeming, sprawling, hub, gem, jewel.
8. Present tense, third person, plain sentences. No lists, no headings, no markdown.
9. Do not write about arriving, approaching, landing, or a first impression from orbit — no sentence beginning "Arrival", and nothing about what is smelled or seen on the way in. Do not frame the inhabitants around what a visitor notices, remarks on or finds. These are entries in a reference work, not a travelogue: describe the place and the people directly. Every one of these entries stands beside hundreds of others, so a reader meets them one after another — a shape used twice is a shape that reads as a template.

Count your sentences and stay inside the ranges above — that is the real limit, and a fifth sentence in the description will be rejected. Keep sentences to a normal length; do not compensate by writing four very long ones. Under-writing is better than padding: two good sentences beat four vague ones.`;

/**
 * The facts, formatted for the model.
 *
 * Deliberately not prose. A labelled block is harder to skim past than a
 * sentence, and every line here is something the game will assert elsewhere.
 *
 * The raw statistics are given as BANDS, because the rules forbid the model
 * repeating a number and a bare figure means nothing to it anyway. What the
 * bands have to be is discriminating, and the first cut of them was not: the
 * thresholds were guessed, and across galaxy 1 they put 207 of 256 worlds in
 * one population band and — worse — left "a large world" matching NOTHING,
 * because the largest radius in the game is 6911 and the threshold was 7000.
 * A band that every world shares is dead weight in the prompt; a band no world
 * reaches is a lie about the galaxy. Same failure as the species prompts
 * drawing 256 men and no women, found the same way: by counting.
 *
 * So these are quartiles, measured over all 2,048 systems in all eight
 * galaxies rather than over galaxy 1 alone — the bands must still discriminate
 * whenever the other seven are generated.
 */
export function factsFor(sys: StarSystem): string {
  const tl = sys.techLevel + 1;
  const band = tl >= 10 ? 'advanced' : tl >= 8 ? 'developed' : tl >= 6 ? 'modest' : 'primitive';
  const pop = sys.population;
  const density = pop >= 43 ? 'heavily populated' : pop >= 35 ? 'populous'
    : pop >= 27 ? 'moderately settled' : 'sparsely settled';
  const wealth = sys.productivity >= 21888 ? 'wealthy'
    : sys.productivity >= 11520 ? 'comfortable'
      : sys.productivity >= 6272 ? 'getting by' : 'poor';
  const size = sys.radius >= 5858 ? 'a large world'
    : sys.radius >= 4867 ? 'a sizeable world'
      : sys.radius >= 3846 ? 'an average-sized world' : 'a small world';

  return [
    `Name: ${sys.name}`,
    `Economy: ${ECONOMY_NAMES[sys.economy]}`,
    `Government: ${GOVERNMENT_NAMES[sys.government]}`,
    `Technology: ${band}`,
    `Settlement: ${density}`,
    `Wealth: ${wealth}`,
    `Size: ${size}`,
    `Inhabitants: ${speciesName(sys)}`,
    `Known for: ${planetDescription(sys)}`,
  ].join('\n');
}

export interface SystemPrompt {
  /** Index within the galaxy — the key the committed record is filed under. */
  index: number;
  /** Carried so a mis-keyed file is a test failure rather than wrong prose. */
  system: string;
  facts: string;
  /** Changes if the rules or this system's facts change. Drives --check. */
  hash: string;
}

/**
 * FNV-1a over the rules plus the facts.
 *
 * Not cryptographic and does not need to be: the only thing it defends
 * against is a regenerated galaxy quietly not matching its committed output.
 * Hand-written so the tool has no dependency and runs the same under node and
 * anywhere else.
 */
export function hashPrompt(facts: string): string {
  return fnv1a(`v${PROMPT_VERSION}\n${SYSTEM_PROMPT}\n${facts}`);
}

/** The hash itself, shared with the patron and the dossier prompts (docs/TODO/191). */
export function fnv1a(text: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < text.length; i += 1) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(16).padStart(8, '0');
}

/**
 * The machine-checkable subset of the rules, in one place.
 *
 * Lives here rather than in the generator because the generator is not the
 * only caller: `test/descriptions.test.ts` runs it over the COMMITTED file.
 * A rule enforced only on the way in is a rule that stops being true the
 * moment anyone hand-edits an entry, and hand-editing an entry is exactly
 * what we would do to fix a bad one.
 *
 * Four of the eight rules cannot be checked mechanically and are not attempted
 * here: no commodity prices, no equipment claims, no invented proper nouns, no
 * mention of the player. Those are the system prompt's job and a reader's.
 * Rule 1's "no written-out numbers" is likewise left to the prompt — "one of
 * the few remaining" is ordinary English and banning it would cost more than
 * it saves. Digits are unambiguous, so digits are what is enforced.
 */
export const BANNED = [
  'bustling', 'vibrant', 'nestled', 'boasts', 'testament', 'tapestry',
  'myriad', 'denizens', 'teeming', 'sprawling', 'hub', 'gem', 'jewel',
] as const;

/**
 * A runaway ceiling, not a style rule. Sentence count is what shapes the
 * prose; this only catches a field that has gone properly wrong.
 *
 * It was 600, and 600 was policing style by accident. The first taste run lost
 * four of twelve Sonnet entries to it at 623, 664, 666 and 687 characters —
 * all of them four well-formed sentences, one landing on exactly 600, which is
 * a model trying to obey a limit it cannot measure. Asking for a character
 * count is asking for something a language model cannot count; asking for four
 * sentences is not. So the prompt now states the limit in sentences and this
 * sits well above where good prose lands.
 */
export const MAX_FIELD = 800;

/**
 * Shapes that read as a template once they are on the fiftieth world.
 *
 * Deliberately narrow: these name the exact formulas the first full run
 * produced at scale, not a general suspicion of the words. "Arrival" anywhere
 * is banned because 207 of 256 entries used it; "visitors notice" because 159
 * did. A world may still be described as hard to reach — it may not be
 * described from the cockpit on the way in.
 */
const FORMULAS: readonly (readonly [RegExp, string])[] = [
  [/\barrival\b/i, 'writes about arriving'],
  [/\b(?:on|upon) (?:arrival|approach|landing)\b/i, 'writes about arriving'],
  [/\bfrom orbit\b/i, 'writes a first impression from orbit'],
  [/\bvisitors?\s+(?:\w+\s+){0,4}?(?:notice|notices|remark|remarks|find|finds|observe|observes)\b/i,
    'frames this around what a visitor notices'],
  [/\bnewcomers?\s+(?:\w+\s+){0,4}?(?:notice|notices|find|finds)\b/i,
    'frames this around what a visitor notices'],
] as const;

/**
 * What a caller may relax, field by field.
 *
 * The defaults are the gazetteer's rules, and every description field takes
 * them. A dossier field (docs/TODO/191) is a different kind of text. A patron
 * speaks to the commander, so a briefing must say "you". A title is a noun
 * phrase with no full stop. The travelogue formulas are a gazetteer's fault,
 * and "report on arrival" is a plain order.
 */
export interface FaultOptions {
  /** the sentence range; the default is by field name, as the descriptions ask */
  sentences?: readonly [number, number];
  /** true lets the text address the reader */
  reader?: boolean;
  /** false skips the travelogue formulas */
  formulas?: boolean;
}

/** Every fault in one field, named. Empty means it passes. */
export function faults(text: string, field: string, opts: FaultOptions = {}): string[] {
  const bad: string[] = [];
  const trimmed = text.trim();

  if (!trimmed) bad.push(`${field} is empty`);
  if (trimmed.length > MAX_FIELD) bad.push(`${field} is ${trimmed.length} chars, over ${MAX_FIELD}`);
  if (/\d/.test(trimmed)) bad.push(`${field} contains a digit`);
  if (!opts.reader && /\byou(?:r|rs|'re|rself)?\b/i.test(trimmed)) {
    bad.push(`${field} addresses the reader`);
  }
  // `<` and `>` are here because a model put them there: Sonnet closed both
  // of Tiraor's fields with a literal `</br>`. The renderer interpolates this
  // text into innerHTML, so markup in a field is not a cosmetic problem — it
  // is content deciding how the page is built. The render site escapes as well
  // (ui/screens.ts); this is the half that stops it being committed at all.
  if (/[\n\r*#_`|<>]/.test(trimmed)) bad.push(`${field} contains markup or a line break`);

  for (const word of BANNED) {
    if (new RegExp(`\\b${word}\\b`, 'i').test(trimmed)) bad.push(`${field} uses "${word}"`);
  }

  // The travelogue formula, and the reason this check is here rather than left
  // to the prompt. The first full run of galaxy 1 read beautifully one entry at
  // a time and read as a template in bulk: 207 of 256 descriptions mentioned
  // arrival, 96 of them ended with the literal words "Arrival brings", and 159
  // of the inhabitants fields said a visitor noticed something. That was the
  // prompt's own fault — it asked for "how it feels to arrive at" and "what a
  // visitor notices", and got exactly that 256 times.
  //
  // The prompt is fixed, but a prompt is a request and this is a gate: each
  // request is generated in isolation, so nothing but a check applied across
  // the set can see a formula forming. A hit here sends the system back for
  // another attempt with the fault named.
  for (const [re, why] of FORMULAS) {
    if (opts.formulas !== false && re.test(trimmed)) bad.push(`${field} ${why}`);
  }

  const sentences = (trimmed.match(/[.!?](?:\s|$)/g) ?? []).length;
  const [lo, hi] = opts.sentences ?? (field === 'description' ? [2, 5] : [1, 4]);
  if (sentences < lo || sentences > hi) {
    bad.push(`${field} has ${sentences} sentences, wanted ${lo}-${hi}`);
  }
  return bad;
}

/**
 * Nineteen system names that are also ordinary English words.
 *
 * Derived by intersecting the 2,023 distinct names across all eight galaxies
 * with the system dictionary, then keeping the ones that could plausibly open
 * a sentence in a planet description — "Rain falls year-round", "Bees were
 * introduced", "Tile roofs". Matching is case-sensitive, which already handles
 * these mid-sentence; this list covers sentence-initial use, where case tells
 * us nothing.
 *
 * The cost is that naming the actual world Rain goes undetected. That is
 * nineteen names out of 2,023, against the certainty of rejecting good prose
 * about weather — the check exists to catch a model wandering off to Lave, and
 * it still does that.
 */
const WORD_NAMES = new Set([
  'Ante', 'Ara', 'Aten', 'Bees', 'Bien', 'Inbe', 'Ra', 'Rabi', 'Rain', 'Rais',
  'Rave', 'Rea', 'Rear', 'Soar', 'Sori', 'Teat', 'Teen', 'Tile', 'Lave',
]);

/**
 * Rule 5's first half, which IS checkable: we hold every system name in the
 * game, so naming another world is detectable rather than a matter of taste.
 * Checked against the whole name pool, not just this galaxy's, because the
 * eight galaxies share it and a stray name is wrong wherever it came from.
 */
let namePool: string[] | null = null;
export function foreignSystemNames(text: string, own: string, canon = ''): string[] {
  if (!namePool) {
    const seen = new Set<string>();
    for (let g = 1; g <= 8; g += 1) for (const s of generateGalaxy(g)) seen.add(s.name);
    namePool = [...seen].filter((n) => !WORD_NAMES.has(n));
  }
  return namePool.filter((n) => n !== own
    // The goat-soup grammar builds its nouns out of the name pool, so a
    // world's own canon line can contain another world's name: Tibedied is
    // "most notable for Tibediedian Vees brandy", and Vees is a system. The
    // first taste run rejected Tibedied's entry for using the one fact it was
    // handed. Whatever the canon line says is by definition not the model
    // wandering off, so it cannot be a fault here.
    && !new RegExp(`\\b${n}\\b`).test(canon)
    && new RegExp(`\\b${n}\\b`).test(text));
}

/** Every system in a galaxy, in index order. */
export function systemPrompts(galaxy: number): SystemPrompt[] {
  return generateGalaxy(galaxy).map((sys) => {
    const facts = factsFor(sys);
    return { index: sys.index, system: sys.name, facts, hash: hashPrompt(facts) };
  });
}

// ---------------------------------------------------------------- cli

const isMain = process.argv[1]?.endsWith('system-prompts.ts');
if (isMain) {
  const args = process.argv.slice(2);
  const galaxy = Number(args.find((a) => /^\d+$/.test(a)) ?? 1);
  const prompts = systemPrompts(galaxy);

  if (args.includes('--json')) {
    process.stdout.write(JSON.stringify({
      galaxy, promptVersion: PROMPT_VERSION, systemPrompt: SYSTEM_PROMPT, prompts,
    }, null, 2));
  } else {
    const sample = [0, 7, 96, 147].filter((i) => i < prompts.length);
    process.stdout.write(`${SYSTEM_PROMPT}\n\n${'='.repeat(70)}\n`);
    for (const i of sample) {
      const p = prompts[i];
      process.stdout.write(`\n--- ${p.index} ${p.system} (${p.hash}) ---\n${p.facts}\n`);
    }
    process.stdout.write(`\n${prompts.length} systems in galaxy ${galaxy}.\n`);
  }
}
